#!/usr/bin/env bash
# ─── Mise ERP — Apple Developer Signing Setup ─────────────────────────────────
# Run this once to configure code signing + notarization for distribution.
# You need an Apple Developer account ($99/year at developer.apple.com).
#
# Usage: bash scripts/setup-apple-signing.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║     Mise ERP — Apple Signing Setup                   ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ─── 1. Check for Xcode tools ────────────────────────────────────────────────
if ! command -v codesign &>/dev/null; then
  echo "→ Installing Xcode Command Line Tools…"
  xcode-select --install
  echo "  Re-run this script after Xcode tools finish installing."
  exit 0
fi
echo "✓ codesign available"

# ─── 2. Check for existing Developer ID certs ────────────────────────────────
echo ""
echo "→ Checking for Developer ID Application certificates…"
CERTS=$(security find-identity -v -p codesigning 2>/dev/null | grep "Developer ID Application" || true)

if [[ -z "$CERTS" ]]; then
  echo ""
  echo "  No Developer ID Application certificate found in your keychain."
  echo ""
  echo "  ┌───────────────────────────────────────────────────────────────┐"
  echo "  │ To get one:                                                   │"
  echo "  │ 1. Open https://developer.apple.com/account/resources/       │"
  echo "  │    certificates/list                                          │"
  echo "  │ 2. Click + → Developer ID Application                        │"
  echo "  │ 3. Follow the CSR instructions → download the .cer file      │"
  echo "  │ 4. Double-click the .cer to add it to your Keychain          │"
  echo "  │ 5. Re-run this script                                         │"
  echo "  └───────────────────────────────────────────────────────────────┘"
  echo ""
  read -r -p "Or paste your full certificate name here (leave blank to exit): " IDENTITY
  [[ -z "$IDENTITY" ]] && exit 1
else
  echo "$CERTS"
  echo ""
  echo "Available identities above. Copy the full name in quotes, e.g.:"
  echo "  Developer ID Application: Jeff Whoever (ABC12345XY)"
  echo ""
  read -r -p "Paste your full certificate name: " IDENTITY
fi

# ─── 3. Get Team ID ──────────────────────────────────────────────────────────
echo ""
echo "Your Team ID is the 10-character code in parentheses in the cert name."
echo "It's also at https://developer.apple.com/account → Membership."
read -r -p "Team ID (10 chars): " TEAM_ID

# ─── 4. Store-Credential for notarization ────────────────────────────────────
echo ""
echo "→ Setting up notarization credential…"
echo "  You need an app-specific password from https://appleid.apple.com"
echo "  (Apple ID → App-Specific Passwords → Generate)"
echo ""
read -r -p "Apple ID email: " APPLE_ID
read -r -s -p "App-specific password: " APP_PASSWORD
echo ""

xcrun notarytool store-credentials "mise-erp-notary" \
  --apple-id "$APPLE_ID" \
  --team-id "$TEAM_ID" \
  --password "$APP_PASSWORD"

echo "✓ Notarization credential stored as 'mise-erp-notary'"

# ─── 5. Write .env.build ──────────────────────────────────────────────────────
ENV_FILE="$(dirname "$0")/../.env.build"
cat > "$ENV_FILE" << ENVEOF
# Generated by setup-apple-signing.sh — do NOT commit this file
export APPLE_IDENTITY="$IDENTITY"
export APPLE_TEAM_ID="$TEAM_ID"
ENVEOF

# Ensure .gitignore covers it
GITIGNORE="$(dirname "$0")/../.gitignore"
grep -q ".env.build" "$GITIGNORE" 2>/dev/null || echo ".env.build" >> "$GITIGNORE"

echo ""
echo "✓ Wrote .env.build (gitignored)"

# ─── 6. Generate .icns if needed ─────────────────────────────────────────────
ICNS="$(dirname "$0")/../assets/icon.icns"
if [[ ! -f "$ICNS" ]]; then
  bash "$(dirname "$0")/make-icns.sh"
fi

# ─── 7. Summary ──────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════"
echo "  ✅  Signing configured!"
echo ""
echo "  To build a signed, notarized DMG:"
echo "    source .env.build && npm run dist"
echo ""
echo "  The DMG will appear in dist-electron/"
echo "══════════════════════════════════════════════════════"
echo ""
